@hostname = localhost:4000


###
POST http://{{hostname}}/register
Content-Type: application/json

{
    "name": "Lauren",
    "login": "lauren",
    "email": "lauren@email.com"
}

###

GET http://{{hostname}}/register?page=1&limit=10&sort=name&asc
Content-Type: application/json