@hostname = localhost:4000


###
POST http://{{hostname}}/register
Content-Type: application/json

{
    "name": "Lauren",
    "login": "lauren",
    "email": "lauren@email.com"
}

###

GET http://{{hostname}}/register/registers?page=3&limit=3
Content-Type: application/json